-- 加载配置项  
require("basic.settings")
require('basic.keybinds')
require("basic.config")
--require('basic.plugins')


require("conf.windline")
require("conf.todo-comments")
require("conf.nvim-tree")
require("conf.Comment")
require("conf.nvim-treesitter")
require("conf.AutoSave")
require("conf.barbar")
require("conf.switch")
require("conf.nvim-autopairs")
require("conf.indent-blankline")
require("conf.hop")
require("conf.nvim-lspconfig")
require("conf.nvim-lsp-installer")
require("conf.lspsaga")
require("conf.fidget")
require("conf.nvim-cmp")
require("conf.vista")
-- require("catppuccin")
require("symbols-outline")
-- require("")
-- require("")
-- require("")
-- require("")
-- require("")

